version: "3.8"

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: fuelphp-app
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html/my_fuel_project
    networks:
      - fuelphp-network

  db:
    build:
      context: ../
      dockerfile: docker/db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fuelphp
    ports:
      - "3306:3306"
    networks:
      - fuelphp-network
    volumes:
      - db_data:/var/lib/mysql

networks:
  fuelphp-network:
    driver: bridge

volumes:
  db_data:
